### PR TITLE
now use `Module#prepend` instead of `class_eval`

### PR DESCRIPTION
**Pull request by bricesanchez**

### CODE REVIEW

**Comment by parndt** [comment]
We could use `Module#prepend` now that we're not supporting older Ruby versions, like this: https://github.com/refinery/refinerycms/blob/e49a6bebefe34bedcca932887f1446f084a23c33/doc/guides/9%20-%20Presenters/1%20-%20Menu%20Presenter.md#allow-show_in_footer-attribute-in-refineryadminpagescontroller

**Comment by bricesanchez** [comment]
Will it works on an ActiveRecord model?

**Comment by parndt** [comment]
Should work as well as, or better than, concerns

**Comment by bricesanchez** [comment]
Could you help me on Gitter now?

**Comment by bricesanchez** [comment]
Now it should be better :)

**Comment by bricesanchez** [comment]
Could we merge it @parndt ?

**Comment by bricesanchez** [comment]
Thanks @parndt !

**Comment by parndt** [comment]
Thank you @bricesanchez  😄

**Pull request merged**
